apiVersion: v1
kind: Service
metadata:
  labels:
    run: muzix-app
  name: muzix-app
spec:
  ports:
  - nodePort: 30185
    port: 8090
    protocol: TCP
    targetPort: 8090
  selector:
    run: muzix-app
  type: NodePort
